apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-guestbook
  template:
    metadata:
      labels:
        app: dotnet-guestbook
    spec:
      containers:
      - name: dotnet-guestbook
        image: docker.io/ariscub/mirrord-dotnet-example:v1
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
